module Constants
    export ALPHABET, ALPHABET_SYMBOLS, ALPHABET_DIM, MAX_STRING_LENGTH,
     BSIZE, PROB_SAME, OUT_CHANNELS, EMBEDDING_DIM, FLAT_SIZE, NUM_BATCHES, 
     MODEL_SAVE_DIR, MODEL_SAVE_SUFFIX
    # Datasets
    ALPHABET = ['A';'T';'C';'G']

    ALPHABET_SYMBOLS = [Symbol(i) for i in ALPHABET]
    ALPHABET_DIM = length(ALPHABET_SYMBOLS)

    MIN_STRING_LENGTH = 64
    MAX_STRING_LENGTH = 512

    BSIZE = 512

    # Model
    OUT_CHANNELS = 8
    EMBEDDING_DIM = 128
    FLAT_SIZE = Int(MAX_STRING_LENGTH / 2 * ALPHABET_DIM * OUT_CHANNELS)

    # Shared
    NUM_BATCHES = 2
    MODEL_SAVE_DIR = "saved_models"
    MODEL_SAVE_SUFFIX = "_synthetic.bson"
end
